name: C/C++ CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    # Update submodules
    - name: Pull submodules recursively
      run: git submodule update --init --recursive

      # Creates build directory. Full paths should be given. 
      # Any parent directories that do not exist will also be created.
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

      # Configure cmake 
      # Creates cmake build prepared files in build directory
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      # Build project in $BUILD_TYPE mode
    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE
